### PR TITLE
Constants and other fixes from PHPStan

### PR DESCRIPTION
**Pull request by szepeviktor**
Discovered by @phpstan

### CODE REVIEW

**Comment by szepeviktor** [comment]
`phpstan.neon.dist`

```yaml
includes:
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - src/
    autoload_files:
        - tests/phpstan/bootstrap.php
        - src/rocket-lazyload-requirements-check.php
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function apply_filters(_ref_array)? invoked with [34567] parameters, 2 required\.$#'
```

`tests/phpstan/bootstrap.php`

```php
<?php

define('ROCKET_LL_VERSION', '0');
define('ROCKET_LL_WP_VERSION', '0');
define('ROCKET_LL_PHP_VERSION', '0');
define('ROCKET_LL_BASENAME', '');
define('ROCKET_LL_PATH', '');
define('ROCKET_LL_ASSETS_URL', '');
define('ROCKET_LL_FRONT_JS_URL', '');
define('ROCKET_LL_INT_MAX', PHP_INT_MAX - 15);

function wr2x_get_pathinfo_from_image_src($image_src) {return $image_src;}

function wr2x_get_retina($file) { if (file_exists($retina_file)) {return $file;} else {return null;}}

function is_amp_endpoint() {return 0 === rand();}
```

**Comment by szepeviktor** [comment]
Hello @Tabrisrp!

Could you lend me a click here?

**Comment by Tabrisrp** [comment]
Hi @szepeviktor 👋 

Thank you for the PR. Quick question, why is the base `\` needed for the constants? Is it compatible with PHP 5.6?

**Comment by szepeviktor** [comment]
@Tabrisrp `src/Plugin.php` is under a namespace, so a simple constant is disambiguous.

`\CONSTANT_NAME` refers to the **global** constant.

**Comment by szepeviktor** [comment]
> Is it compatible with PHP 5.6?

Namespace are in PHP >= 5.3.0

**Comment by Tabrisrp** [comment]
Thank you I validated the changes 👍

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
